#!/bin/bash

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

PROFILE_DIR="$(pwd)"
while [[ "$PROFILE_DIR" != "/" ]]; do
  PROFILE="$PROFILE_DIR/.envyrc"
  if [[ -e $PROFILE ]]; then
    source $PROFILE
    break
  fi

  PROFILE_DIR=$(cd "$PROFILE_DIR"/..; pwd)
done

if [[ -z "$NODEJS_VERSION" ]]; then
  NODEJS_VERSION="v2.2.1"
fi
if [[ -z "$NPM_VERSION" ]]; then
  NPM_VERSION="2.11.2"
fi

NODEJS_BASE_URL="http://nodejs.org/dist/$NODEJS_VERSION/node"
IOJS_BASE_URL="https://iojs.org/dist/$NODEJS_VERSION/iojs"

function get_major_version() {
  local regexp='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
  echo $1 | sed -e "s#$regexp#\1#"
}

install_program() {
  local program_name=$1
  local desired_version=$2
  local custom_install=$3
  local install_path="$ROOT/$program_name/$desired_version"
  local binary_path="$install_path/bin/$program_name"
  local version=""

  if [[ -x "$binary_path" ]]; then
    version="$($binary_path --version)"
    if [[ "$version" == "$desired_version" ]]; then
      return
    fi

    rm -rf $install_path
  fi

  mkdir -p $install_path
  cd $install_path
  $custom_install
  cd -

  version="$($binary_path --version)"
  if [[ "$version" != "$desired_version" ]]; then
    echo "envy: Error installing $program_name"
    exit 1
  fi
}

install_nodejs() {
  local os=$(uname -s | tr "[:upper:]" "[:lower:]")
  if [[ "$(uname -m)" == "x86_64" ]]; then
    local arch="x64"
  else
    local arch="x64"
  fi

  local major=$(get_major_version $NODEJS_VERSION)
  if [[ $major == "0" ]]; then
    local nodejs_url="$NODEJS_BASE_URL-$NODEJS_VERSION-$os-$arch.tar.gz"
  else
    local nodejs_url="$IOJS_BASE_URL-$NODEJS_VERSION-$os-$arch.tar.gz"
  fi

  curl $nodejs_url | tar -xz --strip-components 1
}

install_npm() {
  local temp_npm="$ROOT/node/$NODEJS_VERSION/bin/npm"
  local npm_path="$ROOT/npm/$NPM_VERSION"
  npm_config_prefix="$npm_path" $temp_npm install --global --quiet npm@"$NPM_VERSION"
}

main() {
  install_program "node" "$NODEJS_VERSION" install_nodejs
  install_program "npm" "$NPM_VERSION" install_npm
  local nodejs_path="$ROOT/node/$NODEJS_VERSION/bin"
  local npm_path="$ROOT/npm/$NPM_VERSION/bin"
  local tempfile=$(mktemp)
  local workdir=$(pwd)
  # TODO(gaye): Is there perhaps an easier way to run the command
  #     with the PATH set appropriately? This seems wrong.
  echo -e "PATH=$npm_path:$npm_path/bin:$nodejs_path:$PATH\nnpm_config_prefix=$npm_path $@" > $tempfile
  chmod a+x $tempfile
  exec $tempfile
}

main "$@"
